# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('Hero', wagtail.wagtailcore.blocks.StructBlock([(b'hero_text', wagtail.wagtailcore.blocks.RichTextBlock(blank=True, required=False)), (b'hero_heading', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'link_text', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'hero_image', wagtail.wagtailimages.blocks.ImageChooserBlock())])), ('Paragraph', wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.RichTextBlock(blank=True))])), ('Footer', wagtail.wagtailcore.blocks.StructBlock([(b'footer_text', wagtail.wagtailcore.blocks.RichTextBlock(blank=True)), (b'footer_image', wagtail.wagtailimages.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
